spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;MODE=MYSQL

server:
  servlet:
    context-path: /api/v1

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: ERROR

app:
  security:
    jwtSecret: JWTSuperSecretKey
    jwtExpirationInMs: 604800000

---

spring:
  profiles: test
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
